// Bundle encodé en base64 pour éviter les erreurs de parsing JS
const B64 = 'eyJzaGVldCI6IlJDQyBhdmVjIFByw6lhdmlzIiwiY2VsbHMiOnsiQTIiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkRvbm7DqWVzIGQnZW50csOpZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjIiOnsiZiI6bnVsbCwidiI6bnVsbCwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMyIjp7ImYiOm51bGwsInYiOm51bGwsImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMyI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiRGF0ZSBkZSByw6lmw6lyZW5jZSAobm90aWZpY2F0aW9uIC8gcnVwdHVyZSkifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIzIjp7ImYiOm51bGwsInYiOnsidCI6ImRhdGUiLCJ2IjoiMjAyNy0wNy0wMSJ9LCJmbXQiOiJtbS1kZC15eSIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMzIjp7ImYiOm51bGwsInYiOnsidCI6ImRhdGUiLCJ2IjoiMjAyNy0wNy0wMSJ9LCJmbXQiOiJtbS1kZC15eSIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkE0Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJTYXR1dCBtw6l0YWxsdXJnaWUifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkI0Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJDYWRyZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOnRydWUsIm9wdHMiOlsiQ2FkcmUiLCJOb24tQ2FkcmUiXX0sIkM0Ijp7ImYiOiJCNCIsInYiOnsidCI6InN0ciIsInYiOiJDYWRyZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOnRydWUsIm9wdHMiOlsiQ2FkcmUiLCJOb24tQ2FkcmUiXX0sIkE1Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJEaXNwb3NpdGlmIE1vYmlsaXTDqSBvdSBDRkMgKGZhaXJlIGxlIGNob2l4KSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjUiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkNGQyJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOnRydWUsIm9wdHMiOlsiTW9iaWxpdMOpIiwiQ0ZDIl19LCJDNSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiTW9iaWxpdMOpIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6dHJ1ZSwib3B0cyI6WyJNb2JpbGl0w6kiLCJDRkMiXX0sIkE2Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJEYXRlIGRlIG5haXNzYW5jZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjYiOnsiZiI6bnVsbCwidiI6eyJ0IjoiZGF0ZSIsInYiOiIxOTc1LTA2LTAxIn0sImZtdCI6Im1tLWRkLXl5IiwiaW5wdXQiOnRydWUsIm9wdHMiOm51bGx9LCJDNiI6eyJmIjoiQjYiLCJ2Ijp7InQiOiJkYXRlIiwidiI6IjE5NzUtMDYtMDEifSwiZm10IjoibW0tZGQteXkiLCJpbnB1dCI6dHJ1ZSwib3B0cyI6bnVsbH0sIkE3Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJBZ2UgOiBhbm7DqWVzIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCNyI6eyJmIjoiWUVBUkZSQUMoQjMsQjYsMSkiLCJ2Ijp7InQiOiJudW0iLCJ2Ijo1Mi4wODI4MDgxNDEzMzY5MX0sImZtdCI6IjAuMFwiIGFuc1wiIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzciOnsiZiI6IllFQVJGUkFDKEMzLEM2LDEpIiwidiI6eyJ0IjoibnVtIiwidiI6NTIuMDgyODA4MTQxMzM2OTF9LCJmbXQiOiIwLjBcIiBhbnNcIiIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkE4Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJEYXRlIGQnZW50csOpZSBkYW5zIGwnZW50cmVwcmlzZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjgiOnsiZiI6bnVsbCwidiI6eyJ0IjoiZGF0ZSIsInYiOiIxOTk1LTAxLTAxIn0sImZtdCI6Im1tLWRkLXl5IiwiaW5wdXQiOnRydWUsIm9wdHMiOm51bGx9LCJDOCI6eyJmIjoiQjgiLCJ2Ijp7InQiOiJkYXRlIiwidiI6IjE5OTUtMDEtMDEifSwiZm10IjoibW0tZGQteXkiLCJpbnB1dCI6dHJ1ZSwib3B0cyI6bnVsbH0sIkE5Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJBbmNpZW5uZXTDqSA6IGFubsOpZXMifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkI5Ijp7ImYiOiJZRUFSRlJBQyhCMyxCOCwxKSIsInYiOnsidCI6Im51bSIsInYiOjMyLjQ5NjIyNTAwNjIyMjUyfSwiZm10IjoiMC4wXCIgYW5zXCIiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJDOSI6eyJmIjoiWUVBUkZSQUMoQzMsQzgsMSkiLCJ2Ijp7InQiOiJudW0iLCJ2IjozMi40OTYyMjUwMDYyMjI1Mn0sImZtdCI6IjAuMFwiIGFuc1wiIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTEwIjp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJTYWxhaXJlIGFubnVlbCBicnV0IGRlIHLDqWbDqXJlbmNlIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMTAiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6NzIwMDAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOnRydWUsIm9wdHMiOm51bGx9LCJDMTAiOnsiZiI6IkIxMCIsInYiOnsidCI6Im51bSIsInYiOjcyMDAwLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0Ijp0cnVlLCJvcHRzIjpudWxsfSwiQTExIjp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJTYWxhaXJlIG1lbnN1ZWwgYnJ1dCBkZSByw6lmw6lyZW5jZSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjExIjp7ImYiOiJCMTAvMTIiLCJ2Ijp7InQiOiJudW0iLCJ2Ijo2MDAwLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMxMSI6eyJmIjoiQzEwLzEyIiwidiI6eyJ0IjoibnVtIiwidiI6NjAwMC4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMTIiOnsiZiI6bnVsbCwidiI6bnVsbCwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIxMiI6eyJmIjpudWxsLCJ2IjpudWxsLCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzEyIjp7ImYiOm51bGwsInYiOm51bGwsImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMTMiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkNhbGN1bHMifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIxMyI6eyJmIjpudWxsLCJ2IjpudWxsLCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzEzIjp7ImYiOm51bGwsInYiOm51bGwsImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMTQiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkZvcmNlciBJTEwgPyJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjE0Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJPdWkgKGTDqWZhdXQpIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6dHJ1ZSwib3B0cyI6WyJPdWkgKGTDqWZhdXQpIiwiTm9uIl19LCJDMTQiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6Ik91aSAoZMOpZmF1dCkifSwiZm10IjoiR2VuZXJhbCIsImlucHV0Ijp0cnVlLCJvcHRzIjpbIk91aSAoZMOpZmF1dCkiLCJOb24iXX0sIkExNSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiSW5kZW1uaXTDqSByZXRlbnVlIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMTUiOnsiZiI6Il94bGZuLkxFVChcbiAgICBfeGxwbS5hZ2UsIEI3LFxuICAgIF94bHBtLnN0YXR1dCwgQjQsXG4gICAgX3hscG0uc2FsYWlyZSwgQjExLFxuICAgIF94bHBtLmFuY2llbm5ldGUsIEI5LFxuICAgIF94bHBtLmRpc3Bvc2l0aWYsIEI1LFxuICAgIF94bHBtLmFuY2llbm5ldGVDRkMsIF94bHBtLnNhbGFpcmUqKCRGJDQqTUlOKF94bHBtLmFuY2llbm5ldGUsMTApKyRGJDUqTUFYKF94bHBtLmFuY2llbm5ldGUtMTAsMCkpLFxuICAgIF94bHBtLmluZGVtbml0ZUNGQywgSUYoX3hscG0uYW5jaWVubmV0ZTwkRiQzLDAsX3hscG0uYW5jaWVubmV0ZUNGQyksXG4gICAgX3hscG0uY29lZk1vYmlsaXRlLCBJRihfeGxwbS5hbmNpZW5uZXRlPCRGJDEyLCRGJDQqX3hscG0uYW5jaWVubmV0ZSwkRiQxNCokRiQxMyskRiQxNSpNQVgoX3hscG0uYW5jaWVubmV0ZS0kRiQxMywwKSksXG4gICAgX3hscG0uaW5kZW1uaXRlTW9iaWxpdGUsIF94bHBtLnNhbGFpcmUqX3hscG0uY29lZk1vYmlsaXRlLFxuICAgIF94bHBtLmJvbnVzQWdlLCBJRihBTkQoX3hscG0uYWdlPj01MCxfeGxwbS5hZ2U8NTUsX3hscG0uYW5jaWVubmV0ZT49JEYkNiksTUFYKF94bHBtLmluZGVtbml0ZU1vYmlsaXRlKigxKyRGJDcpLCRGJDkqX3hscG0uc2FsYWlyZSksSUYoQU5EKF94bHBtLmFnZT49NTUsX3hscG0uYWdlPDYwLF94bHBtLmFuY2llbm5ldGU+PSRGJDYpLE1BWChfeGxwbS5pbmRlbW5pdGVNb2JpbGl0ZSooMSskRiQ4KSwkRiQxMCpfeGxwbS5zYWxhaXJlKSxfeGxwbS5pbmRlbW5pdGVNb2JpbGl0ZSkpLFxuICAgIF94bHBtLnBsYWZvbmRNb2JpbGl0ZSwgTUlOKF94bHBtLmJvbnVzQWdlLCRGJDExKl94bHBtLnNhbGFpcmUpLFxuICAgIF94bHBtLnJlZHVjdGlvblNlbmlvciwgSUYoX3hscG0uYWdlPTYxLCRGJDE3LElGKF94bHBtLmFnZT02MiwkRiQxOCxJRihfeGxwbS5hZ2U9NjMsJEYkMTksSUYoX3hscG0uYWdlPj02NCwkRiQyMCwwKSkpKSxcbiAgICBfeGxwbS5yZXN1bHRhdE1vYmlsaXRlLCBJRihfeGxwbS5zdGF0dXQ9XCJDYWRyZVwiLElGKEFORCgkRiQxNj1cIk91aVwiLF94bHBtLmFnZT49NjEpLE1BWChfeGxwbS5wbGFmb25kTW9iaWxpdGUqKDEtX3hscG0ucmVkdWN0aW9uU2VuaW9yKSxfeGxwbS5pbmRlbW5pdGVDRkMpLF94bHBtLnBsYWZvbmRNb2JpbGl0ZSksX3hscG0uaW5kZW1uaXRlQ0ZDKSxcblxuICAgIElGKEIxND1cIk91aSAoZMOpZmF1dClcIixfeGxwbS5pbmRlbW5pdGVDRkMsSUYoX3hscG0uZGlzcG9zaXRpZj1cIkNGQ1wiLF94bHBtLmluZGVtbml0ZUNGQyxfeGxwbS5yZXN1bHRhdE1vYmlsaXRlKSlcbikiLCJ2Ijp7InQiOiJudW0iLCJ2Ijo1OTk5Mi40NTAwMTI0NDUwM30sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzE1Ijp7ImYiOiJfeGxmbi5MRVQoXG4gICAgX3hscG0uYWdlLCBDNyxcbiAgICBfeGxwbS5zdGF0dXQsIEM0LFxuICAgIF94bHBtLnNhbGFpcmUsIEMxMSxcbiAgICBfeGxwbS5hbmNpZW5uZXRlLCBDOSxcbiAgICBfeGxwbS5kaXNwb3NpdGlmLCBDNSxcbiAgICBfeGxwbS5hbmNpZW5uZXRlQ0ZDLCBfeGxwbS5zYWxhaXJlKigkRiQ0Kk1JTihfeGxwbS5hbmNpZW5uZXRlLDEwKSskRiQ1Kk1BWChfeGxwbS5hbmNpZW5uZXRlLTEwLDApKSxcbiAgICBfeGxwbS5pbmRlbW5pdGVDRkMsIElGKF94bHBtLmFuY2llbm5ldGU8JEYkMywwLF94bHBtLmFuY2llbm5ldGVDRkMpLFxuICAgIF94bHBtLmNvZWZNb2JpbGl0ZSwgSUYoX3hscG0uYW5jaWVubmV0ZTwkRiQxMiwkRiQ0Kl94bHBtLmFuY2llbm5ldGUsJEYkMTQqJEYkMTMrJEYkMTUqTUFYKF94bHBtLmFuY2llbm5ldGUtJEYkMTMsMCkpLFxuICAgIF94bHBtLmluZGVtbml0ZU1vYmlsaXRlLCBfeGxwbS5zYWxhaXJlKl94bHBtLmNvZWZNb2JpbGl0ZSxcbiAgICBfeGxwbS5ib251c0FnZSwgSUYoQU5EKF94bHBtLmFnZT49NTAsX3hscG0uYWdlPDU1LF94bHBtLmFuY2llbm5ldGU+PSRGJDYpLE1BWChfeGxwbS5pbmRlbW5pdGVNb2JpbGl0ZSooMSskRiQ3KSwkRiQ5Kl94bHBtLnNhbGFpcmUpLElGKEFORChfeGxwbS5hZ2U+PTU1LF94bHBtLmFnZTw2MCxfeGxwbS5hbmNpZW5uZXRlPj0kRiQ2KSxNQVgoX3hscG0uaW5kZW1uaXRlTW9iaWxpdGUqKDErJEYkOCksJEYkMTAqX3hscG0uc2FsYWlyZSksX3hscG0uaW5kZW1uaXRlTW9iaWxpdGUpKSxcbiAgICBfeGxwbS5wbGFmb25kTW9iaWxpdGUsIE1JTihfeGxwbS5ib251c0FnZSwkRiQxMSpfeGxwbS5zYWxhaXJlKSxcbiAgICBfeGxwbS5yZWR1Y3Rpb25TZW5pb3IsIElGKF94bHBtLmFnZT02MSwkRiQxNyxJRihfeGxwbS5hZ2U9NjIsJEYkMTgsSUYoX3hscG0uYWdlPTYzLCRGJDE5LElGKF94bHBtLmFnZT49NjQsJEYkMjAsMCkpKSksXG4gICAgX3hscG0ucmVzdWx0YXRNb2JpbGl0ZSwgSUYoX3hscG0uc3RhdHV0PVwiQ2FkcmVcIixJRihBTkQoJEYkMTY9XCJPdWlcIixfeGxwbS5hZ2U+PTYxKSxNQVgoX3hscG0ucGxhZm9uZE1vYmlsaXRlKigxLV94bHBtLnJlZHVjdGlvblNlbmlvciksX3hscG0uaW5kZW1uaXRlQ0ZDKSxfeGxwbS5wbGFmb25kTW9iaWxpdGUpLF94bHBtLmluZGVtbml0ZUNGQyksXG5cbiAgICBJRihDMTQ9XCJPdWkgKGTDqWZhdXQpXCIsX3hscG0uaW5kZW1uaXRlQ0ZDLElGKF94bHBtLmRpc3Bvc2l0aWY9XCJDRkNcIixfeGxwbS5pbmRlbW5pdGVDRkMsX3hscG0ucmVzdWx0YXRNb2JpbGl0ZSkpXG4pIiwidiI6eyJ0IjoibnVtIiwidiI6NTk5OTIuNDUwMDEyNDQ1MDN9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkExNiI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiU3VwcmEtbMOpZ2FsZSAoTW9iaWxpdMOpIHVuaXF1ZW1lbnQpIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMTYiOnsiZiI6IklGKEI1PVwiQ0ZDXCIsMCxCMTEqTUlOKCRGJDI1LCRGJDI0KkI5KSkiLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMxNiI6eyJmIjoiSUYoQzU9XCJDRkNcIiwwLEMxMSpNSU4oJEYkMjUsJEYkMjQqQzkpKSIsInYiOnsidCI6Im51bSIsInYiOjE1NTk4MS44ODAwMjk4NjgwN30sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTE3Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJUb3RhbCBpbmRlbW5pdMOpIFJDQyBhdmFudCBwbGFmb25kIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMTciOnsiZiI6IkIxNStCMTYiLCJ2Ijp7InQiOiJudW0iLCJ2Ijo1OTk5Mi40NTAwMTI0NDUwM30sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzE3Ijp7ImYiOiJDMTUrQzE2IiwidiI6eyJ0IjoibnVtIiwidiI6MjE1OTc0LjMzMDA0MjMxMzF9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkExOCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiVG90YWwgaW5kZW1uaXTDqSBSQ0MgYXZlYyBwbGFmb25kIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMTgiOnsiZiI6Il94bGZuLkxFVChcbiAgICBfeGxwbS5tb250YW50TWF4LCBCMTcsXG4gICAgX3hscG0uZGlzcG9zaXRpZiwgQjUsXG4gICAgX3hscG0uc2FsYWlyZVJlZiwgQjExLFxuICAgIF94bHBtLmFuY2llbm5ldGUsIEI5LFxuICAgIF94bHBtLnBsYWZvbmRDRkMsIE1JTihJRigkRiQzMj05OTksX3hscG0ubW9udGFudE1heCwkRiQzMipfeGxwbS5zYWxhaXJlUmVmKSxJRigkRiQzMz05OTksX3hscG0ubW9udGFudE1heCwkRiQzMykpLFxuICAgIF94bHBtLmluZGVtbml0ZUNGQywgSUYoX3hscG0uYW5jaWVubmV0ZTwkRiQzLDAsX3hscG0uc2FsYWlyZVJlZiooJEYkNCpNSU4oX3hscG0uYW5jaWVubmV0ZSwxMCkrJEYkNSpNQVgoX3hscG0uYW5jaWVubmV0ZS0xMCwwKSkpLFxuICAgIF94bHBtLnBsYWZvbmRNb2JpbGl0ZSwgTUlOKCRGJDI2Kl94bHBtLnNhbGFpcmVSZWYsJEYkMjcpLFxuXG4gICAgSUYoX3hscG0ubW9udGFudE1heD1cIlwiLFwiXCIsSUYoX3hscG0uZGlzcG9zaXRpZj1cIkNGQ1wiLE1BWChfeGxwbS5pbmRlbW5pdGVDRkMsTUlOKF94bHBtLm1vbnRhbnRNYXgsIF94bHBtLnBsYWZvbmRDRkMpKSxNQVgoQjE1LE1JTihfeGxwbS5tb250YW50TWF4LCBfeGxwbS5wbGFmb25kTW9iaWxpdGUpKSkpXG4pIiwidiI6eyJ0IjoibnVtIiwidiI6NTk5OTIuNDUwMDEyNDQ1MDN9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMxOCI6eyJmIjoiX3hsZm4uTEVUKFxuICAgIF94bHBtLm1vbnRhbnRNYXgsIEMxNyxcbiAgICBfeGxwbS5kaXNwb3NpdGlmLCBDNSxcbiAgICBfeGxwbS5zYWxhaXJlUmVmLCBDMTEsXG4gICAgX3hscG0uYW5jaWVubmV0ZSwgQzksXG4gICAgX3hscG0ucGxhZm9uZENGQywgTUlOKElGKCRGJDMyPTk5OSxfeGxwbS5tb250YW50TWF4LCRGJDMyKl94bHBtLnNhbGFpcmVSZWYpLElGKCRGJDMzPTk5OSxfeGxwbS5tb250YW50TWF4LCRGJDMzKSksXG4gICAgX3hscG0uaW5kZW1uaXRlQ0ZDLCBJRihfeGxwbS5hbmNpZW5uZXRlPCRGJDMsMCxfeGxwbS5zYWxhaXJlUmVmKigkRiQ0Kk1JTihfeGxwbS5hbmNpZW5uZXRlLDEwKSskRiQ1Kk1BWChfeGxwbS5hbmNpZW5uZXRlLTEwLDApKSksXG4gICAgX3hscG0ucGxhZm9uZE1vYmlsaXRlLCBNSU4oJEYkMjYqX3hscG0uc2FsYWlyZVJlZiwkRiQyNyksXG5cbiAgICBJRihfeGxwbS5tb250YW50TWF4PVwiXCIsXCJcIixJRihfeGxwbS5kaXNwb3NpdGlmPVwiQ0ZDXCIsTUFYKF94bHBtLmluZGVtbml0ZUNGQyxNSU4oX3hscG0ubW9udGFudE1heCwgX3hscG0ucGxhZm9uZENGQykpLE1BWChDMTUsTUlOKF94bHBtLm1vbnRhbnRNYXgsIF94bHBtLnBsYWZvbmRNb2JpbGl0ZSkpKSlcbikiLCJ2Ijp7InQiOiJudW0iLCJ2IjoxMDAwMDAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTE5Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJQbGFmb25kIGF0dGVpbnQgPyJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjE5Ijp7ImYiOiJJRihCMTg8PUIxNyxcIk91aVwiLFwiTm9uXCIpIiwidiI6eyJ0Ijoic3RyIiwidiI6Ik91aSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzE5Ijp7ImYiOiJJRihDMTg8PUMxNyxcIk91aVwiLFwiTm9uXCIpIiwidiI6eyJ0Ijoic3RyIiwidiI6Ik91aSJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTIwIjp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJOb21icmUgZGUgbW9pcyDDqXF1aXZhbGVudCAoVG90YWwgUkNDIGF2ZWMgcGxhZm9uZCkifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyMCI6eyJmIjoiQjE4L0IxMSIsInYiOnsidCI6Im51bSIsInYiOjkuOTk4NzQxNjY4NzQwODM4fSwiZm10IjoiMC4wXCIgbW9pc1wiIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzIwIjp7ImYiOiJDMTgvQzExIiwidiI6eyJ0IjoibnVtIiwidiI6MTYuNjY2NjY2NjY2NjY2NjY4fSwiZm10IjoiMC4wXCIgbW9pc1wiIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTIxIjp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJOaXZlYXUgZGUgcsOpbXVuw6lyYXRpb24ifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyMSI6eyJmIjoiSUYoQjU9XCJDRkNcIiwkRiQzNSxJRihCNzw1MCwkRiQzMCwkRiQzMSkpIiwidiI6eyJ0IjoibnVtIiwidiI6MC43fSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJDMjEiOnsiZiI6IklGKEM1PVwiQ0ZDXCIsJEYkMzUsSUYoQzc8NTAsJEYkMzAsJEYkMzEpKSIsInYiOnsidCI6Im51bSIsInYiOjAuOH0sImZtdCI6IjAlIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTIyIjp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJSw6ltdW7DqXJhdGlvbiBtZW5zdWVsbGUgYnJ1dCBwZW5kYW50IGxlIGRpc3Bvc2l0aWYifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyMiI6eyJmIjoiQjExKkIyMSIsInYiOnsidCI6Im51bSIsInYiOjQyMDAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzIyIjp7ImYiOiJDMTEqQzIxIiwidiI6eyJ0IjoibnVtIiwidiI6NDgwMC4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMjMiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkR1csOpZSBkdSBwcsOpYXZpcyJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjIzIjp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjAuMH0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJDMjMiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC4wfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkEyNCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiRHVyw6llIG1heGltYWxlIGR1IGRpc3Bvc2l0aWYifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyNCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjozNi4wfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMyNCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjoxNS4wfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkEyNSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiRGF0ZSBkZSBzb3J0aWUgZHUgZGlzcG9zaXRpZiJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjI1Ijp7ImYiOiJFREFURShCMyxCMjQpIiwidiI6eyJ0IjoiZGF0ZSIsInYiOiIyMDMwLTA3LTAxIn0sImZtdCI6Im1tLWRkLXl5IiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzI1Ijp7ImYiOiJFREFURShDMyxDMjQpIiwidiI6eyJ0IjoiZGF0ZSIsInYiOiIyMDI4LTEwLTAxIn0sImZtdCI6Im1tLWRkLXl5IiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTI2Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJSw6ltdW7DqXJhdGlvbiBUb3RhbGUifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyNiI6eyJmIjoiQjIyKihCMjQrQjIzKigkRiQzNi9CMjEtMSkpIiwidiI6eyJ0IjoibnVtIiwidiI6MTUxMjAwLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMyNiI6eyJmIjoiQzIyKihDMjQrQzIzKigkRiQzNi9DMjEtMSkpIiwidiI6eyJ0IjoibnVtIiwidiI6NzIwMDAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQTI3Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJSw6ltdW7DqXJhdGlvbiB0b3RhbGUgeSBjb21wcmlzIGluZGVtbml0w6kgdG90YWxlIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMjciOnsiZiI6IkIyNitCMTgiLCJ2Ijp7InQiOiJudW0iLCJ2IjoyMTExOTIuNDUwMDEyNDQ1MDR9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMyNyI6eyJmIjoiQzI2K0MxOCIsInYiOnsidCI6Im51bSIsInYiOjE3MjAwMC4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMjgiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IlLDqW11bsOpcmF0aW9uIG1veWVubmUgcGVuZGFudCBsYSBkdXLDqWUgZHUgZGlzcG9zaXRpZiJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjI4Ijp7ImYiOiJCMjcvQjI0IiwidiI6eyJ0IjoibnVtIiwidiI6NTg2Ni40NTY5NDQ3OTAxNH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzI4Ijp7ImYiOiJDMjcvQzI0IiwidiI6eyJ0IjoibnVtIiwidiI6MTE0NjYuNjY2NjY2NjY2NjY2fSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMjkiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IkVjYXJ0IGRlIHNhbGFpcmUgYnJ1dCB2cyBzYWxhaXJlIGRlIHJlZmVyZW5jZSDigqwifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIyOSI6eyJmIjoiQjI4LUIxMSIsInYiOnsidCI6Im51bSIsInYiOi0xMzMuNTQzMDU1MjA5ODU5NjN9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMyOSI6eyJmIjoiQzI4LUMxMSIsInYiOnsidCI6Im51bSIsInYiOjU0NjYuNjY2NjY2NjY2NjY2fSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMzAiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6Ik5vbWJyZSBkZSBtb2lzIMOpcXVpdmFsZW50IHZzIHNhbGFpcmUgbWVuc3VlbCBicnV0IGRlIHLDqWbDqXJlbmNlIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJCMzAiOnsiZiI6IkIyNy9CMTEiLCJ2Ijp7InQiOiJudW0iLCJ2IjozNS4xOTg3NDE2Njg3NDA4NH0sImZtdCI6IjAuMFwiIG1vaXNcIiIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMzMCI6eyJmIjoiQzI3L0MxMSIsInYiOnsidCI6Im51bSIsInYiOjI4LjY2NjY2NjY2NjY2NjY2OH0sImZtdCI6IjAuMFwiIG1vaXNcIiIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkEzMSI6eyJmIjpudWxsLCJ2IjpudWxsLCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjMxIjp7ImYiOm51bGwsInYiOm51bGwsImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJDMzEiOnsiZiI6bnVsbCwidiI6bnVsbCwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkEzMiI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiQ290aXNhdGlvbnMifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIzMiI6eyJmIjpudWxsLCJ2IjpudWxsLCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzMyIjp7ImYiOm51bGwsInYiOm51bGwsImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMzMiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IlBhcnQgU291bWlzZSBjb3Rpc2F0aW9ucyBVUlNBRkYifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkIzMyI6eyJmIjoiQjE4LUlGKEIxOD49MTAqJEYkMjEsMCxNSU4oQjE4LDIqJEYkMjEpKSIsInYiOnsidCI6Im51bSIsInYiOjAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQzMzIjp7ImYiOiJDMTgtSUYoQzE4Pj0xMCokRiQyMSwwLE1JTihDMTgsMiokRiQyMSkpIiwidiI6eyJ0IjoibnVtIiwidiI6Mzg4MC4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGx9LCJBMzQiOnsiZiI6bnVsbCwidiI6eyJ0Ijoic3RyIiwidiI6IlBhcnQgc291bWlzZSBDU0cvQ1JEUyJ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsfSwiQjM0Ijp7ImYiOiJJRihCMTg+PTEwKiRGJDIxLEIxOCxCMTgtTUlOKEIxOCxNSU4oQjE1LEIxOC1CMzMpKSkiLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkMzNCI6eyJmIjoiSUYoQzE4Pj0xMCokRiQyMSxDMTgsQzE4LU1JTihDMTgsTUlOKEMxNSxDMTgtQzMzKSkpIiwidiI6eyJ0IjoibnVtIiwidiI6NDAwMDcuNTQ5OTg3NTU0OTd9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbH0sIkYzIjp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjguMH0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGNCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjI1fSwiZm10IjoiMC4wMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkY1Ijp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjAuMzMzMzMzMzMzMzMzMzMzM30sImZtdCI6IjAuMDAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGNiI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2Ijo1LjB9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjciOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC4yfSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGOCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjN9LCJmbXQiOiIwJSIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkY5Ijp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjMuMH0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMTAiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6Ni4wfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYxMSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjoxOC4wfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYxMiI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2Ijo4LjB9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjEzIjp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjcuMH0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMTQiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC4yfSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYxNSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjZ9LCJmbXQiOiJHZW5lcmFsIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjE2Ijp7ImYiOm51bGwsInYiOnsidCI6InN0ciIsInYiOiJPdWkifSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYxNyI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjowLjA1fSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMTgiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC4xfSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMTkiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC4yfSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMjAiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC40fSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMjEiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6NDgwNjAuMH0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMjIiOnsiZiI6bnVsbCwidiI6bnVsbCwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYyMyI6eyJmIjpudWxsLCJ2Ijp7InQiOiJzdHIiLCJ2IjoiVmFsZXVyIn0sImZtdCI6IkdlbmVyYWwiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMjQiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC44fSwiZm10IjoiR2VuZXJhbCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYyNSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2Ijo5OTkuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjI2Ijp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjE4LjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYyNyI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjoxMDAwMDAuMH0sImZtdCI6IiMsIyMwIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjI4Ijp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjEyLjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYyOSI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjoxNS4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMzAiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC43NX0sImZtdCI6IjAlIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjMxIjp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjAuOH0sImZtdCI6IjAlIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfSwiRjMyIjp7ImYiOm51bGwsInYiOnsidCI6Im51bSIsInYiOjk5OS4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMzMiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6OTk5LjB9LCJmbXQiOiIjLCMjMCIsImlucHV0IjpmYWxzZSwib3B0cyI6bnVsbCwiaXNQYXJhbSI6dHJ1ZX0sIkYzNCI6eyJmIjpudWxsLCJ2Ijp7InQiOiJudW0iLCJ2IjozNi4wfSwiZm10IjoiIywjIzAiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMzUiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6MC43fSwiZm10IjoiMCUiLCJpbnB1dCI6ZmFsc2UsIm9wdHMiOm51bGwsImlzUGFyYW0iOnRydWV9LCJGMzYiOnsiZiI6bnVsbCwidiI6eyJ0IjoibnVtIiwidiI6OS45OX0sImZtdCI6IjAlIiwiaW5wdXQiOmZhbHNlLCJvcHRzIjpudWxsLCJpc1BhcmFtIjp0cnVlfX0sInJlbmRlciI6W1siQTIiLCJCMiIsIkMyIl0sWyJBMyIsIkIzIiwiQzMiXSxbIkE0IiwiQjQiLCJDNCJdLFsiQTUiLCJCNSIsIkM1Il0sWyJBNiIsIkI2IiwiQzYiXSxbIkE3IiwiQjciLCJDNyJdLFsiQTgiLCJCOCIsIkM4Il0sWyJBOSIsIkI5IiwiQzkiXSxbIkExMCIsIkIxMCIsIkMxMCJdLFsiQTExIiwiQjExIiwiQzExIl0sWyJBMTIiLCJCMTIiLCJDMTIiXSxbIkExMyIsIkIxMyIsIkMxMyJdLFsiQTE0IiwiQjE0IiwiQzE0Il0sWyJBMTUiLCJCMTUiLCJDMTUiXSxbIkExNiIsIkIxNiIsIkMxNiJdLFsiQTE3IiwiQjE3IiwiQzE3Il0sWyJBMTgiLCJCMTgiLCJDMTgiXSxbIkExOSIsIkIxOSIsIkMxOSJdLFsiQTIwIiwiQjIwIiwiQzIwIl0sWyJBMjEiLCJCMjEiLCJDMjEiXSxbIkEyMiIsIkIyMiIsIkMyMiJdLFsiQTIzIiwiQjIzIiwiQzIzIl0sWyJBMjQiLCJCMjQiLCJDMjQiXSxbIkEyNSIsIkIyNSIsIkMyNSJdLFsiQTI2IiwiQjI2IiwiQzI2Il0sWyJBMjciLCJCMjciLCJDMjciXSxbIkEyOCIsIkIyOCIsIkMyOCJdLFsiQTI5IiwiQjI5IiwiQzI5Il0sWyJBMzAiLCJCMzAiLCJDMzAiXSxbIkEzMSIsIkIzMSIsIkMzMSJdLFsiQTMyIiwiQjMyIiwiQzMyIl0sWyJBMzMiLCJCMzMiLCJDMzMiXSxbIkEzNCIsIkIzNCIsIkMzNCJdXSwicGFyYW1Sb3dzIjpbeyJ0eXBlIjoiaGVhZGVyIiwibGFiZWwiOiJQYXJhbcOodHJlcyBsw6lnYXV4IChQYXIgZMOpZmF1dCwgbmUgcGFzIG1vZGlmaWVyKSJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYzIiwibGFiZWwiOiJJTEwgLSBBbmNpZW5uZXTDqSBtaW5pbWFsZSAobW9pcykiLCJjb21tZW50IjoiRHJvaXQgw6AgaW5kZW1uaXTDqSBzaSBhbmNpZW5uZXTDqSA+PSA4IG1vaXMgKHLDqGdsZSBsw6lnYWxlICsgQ0NOKSJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkY0IiwibGFiZWwiOiJJTEwgLSBUYXV4IDAtMTAgYW5zIChtb2lzL2FuKSIsImNvbW1lbnQiOiIxLzQgbW9pcyBwYXIgYW5uw6llIHN1ciBsZXMgMTAgcHJlbWnDqHJlcyBhbm7DqWVzIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjUiLCJsYWJlbCI6IklMTCAtIFRhdXggPjEwIGFucyAobW9pcy9hbikiLCJjb21tZW50IjoiMS8zIG1vaXMgcGFyIGFubsOpZSBhdS1kZWzDoCBkZSAxMCBhbnMifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGNiIsImxhYmVsIjoiSUxDIC0gQW5jaWVubmV0w6kgbWluaSByZXF1aXNlIChhbnMpIiwiY29tbWVudCI6IkNvbmRpdGlvbiBkJ2FuY2llbm5ldMOpIHBvdXIgbWFqb3JhdGlvbnMgY2FkcmVzIDUwLTYwIGFucyJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkY3IiwibGFiZWwiOiJJTEMgLSBNYWpvcmF0aW9uIMOiZ2UgNTAtNTUgKG1vaXMpIiwiY29tbWVudCI6Ik1ham9yYXRpb24gKzIwJSAoY2FkcmVzKSBzaSA1MCA8PSDDomdlIDwgNTUgZXQgYW5jaWVubmV0w6kgPj0gNSBhbnMifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGOCIsImxhYmVsIjoiSUxDIC0gTWFqb3JhdGlvbiDDomdlIDU1LTYwIChtb2lzKSIsImNvbW1lbnQiOiJNYWpvcmF0aW9uICszMCUgKGNhZHJlcykgc2kgNTUgPD0gw6JnZSA8IDYwIGV0IGFuY2llbm5ldMOpID49IDUgYW5zIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjkiLCJsYWJlbCI6IklMQyAtIFBsYW5jaGVyIDUwLTU1IChtb2lzKSIsImNvbW1lbnQiOiJQbGFuY2hlciA6IGF1IG1vaW5zIDMgbW9pcyAoY2FkcmVzIDUwLTU1LCBhbmNpZW5uZXTDqSA+PSA1IGFucykifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMTAiLCJsYWJlbCI6IklMQyAtIFBsYW5jaGVyIDU1LTYwIChtb2lzKSIsImNvbW1lbnQiOiJQbGFuY2hlciA6IGF1IG1vaW5zIDYgbW9pcyAoY2FkcmVzIDU1LTYwLCBhbmNpZW5uZXTDqSA+PSA1IGFucykifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMTEiLCJsYWJlbCI6IklMQyAtIFBsYWZvbmQgKG1vaXMpIiwiY29tbWVudCI6IlBsYWZvbmQgOiAxOCBtb2lzIGRlIHNhbGFpcmUgZGUgcsOpZsOpcmVuY2UgKGNhZHJlcykifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMTIiLCJsYWJlbCI6IklMQyAtIFNldWlsIGFuY2llbm5ldMOpIHLDqWdpbWUgY2FkcmVzIChhbm7DqWVzKSIsImNvbW1lbnQiOiJBcnQuIDc1LjMuMS4yIDogcsOpZ2ltZSByZW5mb3Jjw6kgw6AgcGFydGlyIGRlIDggYW5zIChGLEcsSCxJKSJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYxMyIsImxhYmVsIjoiSUxDIC0gU2V1aWwgY2hhbmdlbWVudCBjb2VmZiAoYW5uw6llcykiLCJjb21tZW50IjoiQXJ0LiA3NS4zLjEuMiA6IGNoYW5nZW1lbnQgZGUgY29lZmYgw6AgNyBhbnMgKEYsRyxILEkpIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjE0IiwibGFiZWwiOiJJTEMgLSBDb2VmZiAxLzUgKGp1c3F14oCZw6AgNyBhbnMpIiwiY29tbWVudCI6IkFydC4gNzUuMy4xLjIgOiAxLzUgbW9pcyBwYXIgYW5uw6llIGp1c3F14oCZw6AgNyBhbnMgKEYsRyxILEkpIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjE1IiwibGFiZWwiOiJJTEMgLSBDb2VmZiAzLzUgKGF1LWRlbMOgIGRlIDcgYW5zKSIsImNvbW1lbnQiOiJBcnQuIDc1LjMuMS4yIDogMy81IG1vaXMgcGFyIGFubsOpZSBhdS1kZWzDoCBkZSA3IGFucyAoRixHLEgsSSkifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMTYiLCJsYWJlbCI6IklMQyAtIE1pbm9yYXRpb24iLCJjb21tZW50IjoiTm9uIGFwcGxpY2FibGUgc2kgcGFzIHRhdXggcGxlaW4gb3UgcmV0cmFpdGUgY29tcGwuIGF2ZWMgYWJhdHRlbWVudCJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYxNyIsImxhYmVsIjoiSUxDIC0gTWlub3JhdGlvbiA2MSBhbnMiLCJjb21tZW50IjoiRMOpY290ZSA6IC01JSDDoCA2MSBhbnMgKGNhZHJlcykifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMTgiLCJsYWJlbCI6IklMQyAtIE1pbm9yYXRpb24gNjIgYW5zIiwiY29tbWVudCI6IkTDqWNvdGUgOiAtMTAlIMOgIDYyIGFucyAoY2FkcmVzKSJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYxOSIsImxhYmVsIjoiSUxDIC0gTWlub3JhdGlvbiA2MyBhbnMiLCJjb21tZW50IjoiRMOpY290ZSA6IC0yMCUgw6AgNjMgYW5zIChjYWRyZXMpIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjIwIiwibGFiZWwiOiJJTEMgLSBNaW5vcmF0aW9uIDY0KyBhbnMiLCJjb21tZW50IjoiRMOpY290ZSA6IC00MCUgw6AgNjQgYW5zIGV0IHBsdXMgKGNhZHJlcykifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMjEiLCJsYWJlbCI6IlBBU1MgYW5udWVsIiwiY29tbWVudCI6IlBsYWZvbmQgQW5udWVsIFPDqWN1cml0w6kgU29jaWFsZSAyMDI2In0seyJ0eXBlIjoiaGVhZGVyIiwibGFiZWwiOiJOw6lnb2NpYXRpb24ifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMjQiLCJsYWJlbCI6Ik1vYmlsaXTDqSAtIENvZWZmaWNpZW50IHN1cHJhLWzDqWdhbGUgKG1vaXMvYW4pIiwiY29tbWVudCI6IkNvZWZmaWNpZW50IGVuIG1vaXMgZGUgc2FsYWlyZSBwYXIgYW5uw6llIGQnYW5jaWVubmV0w6kifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMjUiLCJsYWJlbCI6Ik1vYmlsaXTDqSAtIFBsYWZvbmQgc3VwcmEtbMOpZ2FsZSBtb2JpbGl0w6kgKG1vaXMpIiwiY29tbWVudCI6IlBsYWZvbmQgZW4gbW9pcyBwb3VyIGxhIHN1cHJhICg5OTkgPSBwYXMgZGUgcGxhZm9uZCkifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMjYiLCJsYWJlbCI6Ik1vYmlsaXTDqSAtIFBsYWZvbmQgdG90YWwgUkNDIChtb2lzKSIsImNvbW1lbnQiOiJQbGFmb25kIGV4cHJpbcOpIGVuIG5vbWJyZSBkZSBtb2lzIGRlIHNhbGFpcmUgKDk5OSA9IHBhcyBkZSBwbGFmb25kKSJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYyNyIsImxhYmVsIjoiTW9iaWxpdMOpIC0gUGxhZm9uZCB0b3RhbCBSQ0MgKOKCrCkiLCJjb21tZW50IjoiUGxhZm9uZCBleHByaW3DqSBlbiBldXJvcyAoOTk5ID0gcGFzIGRlIHBsYWZvbmQpIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjI4IiwibGFiZWwiOiJNb2JpbGl0w6kgLSBEdXLDqWUgbWF4IDwgNTAgYW5zIChtb2lzKSIsImNvbW1lbnQiOiJEdXLDqWUgbWF4aW1hbGUgc2kgZGlzcG9zaXRpZiBtb2JpbGl0w6kgZXQgw6JnZSA8IDUwIGFucyJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYyOSIsImxhYmVsIjoiTW9iaWxpdMOpIC0gRHVyw6llIG1heCDiiaUgNTAgYW5zIChtb2lzKSIsImNvbW1lbnQiOiJEdXLDqWUgbWF4aW1hbGUgc2kgZGlzcG9zaXRpZiBtb2JpbGl0w6kgZXQgw6JnZSDiiaUgNTAgYW5zIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjMwIiwibGFiZWwiOiJNb2JpbGl0w6kgLSBUYXV4IHLDqW11bsOpcmF0aW9uIDwgNTAgYW5zIiwiY29tbWVudCI6IlLDqW11bsOpcmF0aW9uIDogbW9iaWxpdMOpLCDDomdlIDwgNTAgYW5zIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjMxIiwibGFiZWwiOiJNb2JpbGl0w6kgLSBUYXV4IHLDqW11bsOpcmF0aW9uIOKJpSA1MCBhbnMiLCJjb21tZW50IjoiUsOpbXVuw6lyYXRpb24gOiBtb2JpbGl0w6ksIMOiZ2Ug4omlIDUwIGFucyJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYzMiIsImxhYmVsIjoiQ0ZDIC0gUGxhZm9uZCB0b3RhbCBSQ0MgKG1vaXMpIiwiY29tbWVudCI6IlBsYWZvbmQgZXhwcmltw6kgZW4gbm9tYnJlIGRlIG1vaXMgZGUgc2FsYWlyZSAoOTk5ID0gcGFzIGRlIHBsYWZvbmQpIn0seyJ0eXBlIjoicGFyYW0iLCJhZGRyIjoiRjMzIiwibGFiZWwiOiJDRkMgLSBQbGFmb25kIHRvdGFsIFJDQyAo4oKsKSIsImNvbW1lbnQiOiJQbGFmb25kIGV4cHJpbcOpIGVuIGV1cm9zICg5OTkgPSBwYXMgZGUgcGxhZm9uZCkifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMzQiLCJsYWJlbCI6IkNGQyAtIER1csOpZSBtYXggKG1vaXMpIiwiY29tbWVudCI6IkR1csOpZSBtYXhpbWFsZSBzaSBkaXNwb3NpdGlmIENGQyJ9LHsidHlwZSI6InBhcmFtIiwiYWRkciI6IkYzNSIsImxhYmVsIjoiQ0ZDIC0gVGF1eCByw6ltdW7DqXJhdGlvbiIsImNvbW1lbnQiOiJSw6ltdW7DqXJhdGlvbiA6IENGQyA9IDY1JSBkdSBzYWxhaXJlIG1lbnN1ZWwgZGUgcsOpZsOpcmVuY2UifSx7InR5cGUiOiJwYXJhbSIsImFkZHIiOiJGMzYiLCJsYWJlbCI6IlRhdXggZHUgcHLDqWF2aXMiLCJjb21tZW50IjoiVGF1eCBkdSBwcsOpYXZpcyAoOTk5JSA9IFBhcyBkZSBwcsOpYXZpcykifV0sInBhcmFtRGVmYXVsdHMiOnsiRjMiOnsidCI6Im51bSIsInYiOjguMH0sIkY0Ijp7InQiOiJudW0iLCJ2IjowLjI1fSwiRjUiOnsidCI6Im51bSIsInYiOjAuMzMzMzMzMzMzMzMzMzMzM30sIkY2Ijp7InQiOiJudW0iLCJ2Ijo1LjB9LCJGNyI6eyJ0IjoibnVtIiwidiI6MC4yfSwiRjgiOnsidCI6Im51bSIsInYiOjAuM30sIkY5Ijp7InQiOiJudW0iLCJ2IjozLjB9LCJGMTAiOnsidCI6Im51bSIsInYiOjYuMH0sIkYxMSI6eyJ0IjoibnVtIiwidiI6MTguMH0sIkYxMiI6eyJ0IjoibnVtIiwidiI6OC4wfSwiRjEzIjp7InQiOiJudW0iLCJ2Ijo3LjB9LCJGMTQiOnsidCI6Im51bSIsInYiOjAuMn0sIkYxNSI6eyJ0IjoibnVtIiwidiI6MC42fSwiRjE2Ijp7InQiOiJzdHIiLCJ2IjoiT3VpIn0sIkYxNyI6eyJ0IjoibnVtIiwidiI6MC4wNX0sIkYxOCI6eyJ0IjoibnVtIiwidiI6MC4xfSwiRjE5Ijp7InQiOiJudW0iLCJ2IjowLjJ9LCJGMjAiOnsidCI6Im51bSIsInYiOjAuNH0sIkYyMSI6eyJ0IjoibnVtIiwidiI6NDgwNjAuMH0sIkYyMiI6bnVsbCwiRjIzIjp7InQiOiJzdHIiLCJ2IjoiVmFsZXVyIn0sIkYyNCI6eyJ0IjoibnVtIiwidiI6MC44fSwiRjI1Ijp7InQiOiJudW0iLCJ2Ijo5OTkuMH0sIkYyNiI6eyJ0IjoibnVtIiwidiI6MTguMH0sIkYyNyI6eyJ0IjoibnVtIiwidiI6MTAwMDAwLjB9LCJGMjgiOnsidCI6Im51bSIsInYiOjEyLjB9LCJGMjkiOnsidCI6Im51bSIsInYiOjE1LjB9LCJGMzAiOnsidCI6Im51bSIsInYiOjAuNzV9LCJGMzEiOnsidCI6Im51bSIsInYiOjAuOH0sIkYzMiI6eyJ0IjoibnVtIiwidiI6OTk5LjB9LCJGMzMiOnsidCI6Im51bSIsInYiOjk5OS4wfSwiRjM0Ijp7InQiOiJudW0iLCJ2IjozNi4wfSwiRjM1Ijp7InQiOiJudW0iLCJ2IjowLjd9LCJGMzYiOnsidCI6Im51bSIsInYiOjkuOTl9fSwiZWRpdGFibGVBIjpbIkIxMCIsIkIxNCIsIkI0IiwiQjUiLCJCNiIsIkI4IiwiQzEwIiwiQzE0IiwiQzQiLCJDNSIsIkM2IiwiQzgiXX0=';
const BUNDLE = JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(B64), c => c.charCodeAt(0))));

const PARAM_KEY = 'rcc_params_v1';

function toDate(v){
  if(v==null) return null;
  if(v instanceof Date) return v;
  if(typeof v==='string' && /^\d{4}-\d{2}-\d{2}$/.test(v)) return new Date(v+'T00:00:00');
  const d=new Date(v);
  return isNaN(d.getTime())? null : d;
}
function formatDateFR(d){
  if(!d) return '';
  const dd=String(d.getDate()).padStart(2,'0');
  const mm=String(d.getMonth()+1).padStart(2,'0');
  const yy=d.getFullYear();
  return `${dd}/${mm}/${yy}`;
}
function daysInYear(y){ return (new Date(y,1,29).getMonth()===1)?366:365; }
function diffDays(d1,d2){
  const t1=Date.UTC(d1.getFullYear(),d1.getMonth(),d1.getDate());
  const t2=Date.UTC(d2.getFullYear(),d2.getMonth(),d2.getDate());
  return (t2-t1)/86400000;
}
function yearfracActualActual(d1,d2){
  if(!d1 || !d2) return 0;
  if(d2<d1){ const tmp=d1; d1=d2; d2=tmp; }
  const y1=d1.getFullYear(), y2=d2.getFullYear();
  if(y1===y2) return diffDays(d1,d2)/daysInYear(y1);
  let frac = diffDays(d1, new Date(y1+1,0,1))/daysInYear(y1);
  for(let y=y1+1; y<y2; y++) frac += 1;
  frac += diffDays(new Date(y2,0,1), d2)/daysInYear(y2);
  return frac;
}
function edate(d, months){
  d=toDate(d); if(!d) return null;
  const m=Number(months)||0;
  const y=d.getFullYear(), mo=d.getMonth(), day=d.getDate();
  const target=new Date(y, mo+m, 1);
  const last=new Date(target.getFullYear(), target.getMonth()+1, 0).getDate();
  target.setDate(Math.min(day,last));
  return target;
}

function tokenize(s){
  const out=[]; let i=0;
  const isDigit=c=>c>='0'&&c<='9';
  const isAlpha=c=>/^[A-Za-z_]$/.test(c);
  while(i<s.length){
    const c=s[i];
    if(/\s/.test(c)){ i++; continue; }
    if(c==='"'){
      let j=i+1, str='';
      while(j<s.length && s[j]!=='"'){ str+=s[j++]; }
      out.push({t:'str',v:str}); i=j+1; continue;
    }
    const two=s.slice(i,i+2);
    if(['<=','>=','<>'].includes(two)){ out.push({t:'op',v:two}); i+=2; continue; }
    if(['+','-','*','/','^','(',')',',','=','<','>'].includes(c)){
      out.push({t:(c===','?'comma':(c==='('||c===')'?'paren':'op')),v:c}); i++; continue;
    }
    if(isDigit(c) || (c==='.' && isDigit(s[i+1]))){
      let j=i; while(j<s.length && /[0-9.]/.test(s[j])) j++;
      out.push({t:'num',v:Number(s.slice(i,j))}); i=j; continue;
    }
    const cellMatch=s.slice(i).match(/^\$?[A-Z]{1,3}\$?\d+/);
    if(cellMatch){ out.push({t:'cell',v:cellMatch[0].replaceAll('$','')}); i+=cellMatch[0].length; continue; }
    if(isAlpha(c) || c==='.'){
      let j=i; while(j<s.length && /[A-Za-z0-9_\.]/.test(s[j])) j++;
      out.push({t:'ident',v:s.slice(i,j)}); i=j; continue;
    }
    // ignore unknown char
    i++;
  }
  return out;
}

function Parser(tokens){
  let p=0;
  const peek=()=>tokens[p];
  const take=()=>tokens[p++];
  const match=(t,v)=>{ const k=peek(); if(!k||k.t!==t||(v!=null && k.v!==v)) return false; p++; return true; };

  function expr(){ return cmp(); }
  function cmp(){
    let n=add();
    while(true){
      const k=peek();
      if(k && k.t==='op' && ['=','<>','<','>','<=','>='].includes(k.v)){
        const op=take().v; const r=add(); n={type:'bin',op,left:n,right:r};
      } else break;
    }
    return n;
  }
  function add(){
    let n=mul();
    while(true){
      const k=peek();
      if(k && k.t==='op' && (k.v==='+'||k.v==='-')){ const op=take().v; const r=mul(); n={type:'bin',op,left:n,right:r}; }
      else break;
    }
    return n;
  }
  function mul(){
    let n=pow();
    while(true){
      const k=peek();
      if(k && k.t==='op' && (k.v==='*'||k.v==='/')){ const op=take().v; const r=pow(); n={type:'bin',op,left:n,right:r}; }
      else break;
    }
    return n;
  }
  function pow(){
    let n=unary();
    const k=peek();
    if(k && k.t==='op' && k.v==='^'){ take(); const r=unary(); n={type:'bin',op:'^',left:n,right:r}; }
    return n;
  }
  function unary(){
    const k=peek();
    if(k && k.t==='op' && (k.v==='+'||k.v==='-')){ const op=take().v; return {type:'un',op,expr:unary()}; }
    return prim();
  }
  function prim(){
    const k=peek();
    if(!k) return {type:'num',v:0};
    if(match('num')) return {type:'num',v:tokens[p-1].v};
    if(match('str')) return {type:'str',v:tokens[p-1].v};
    if(match('cell')) return {type:'cell',v:tokens[p-1].v};
    if(match('ident')){
      const ident=tokens[p-1].v;
      if(match('paren','(')){
        const args=[];
        if(!match('paren',')')){
          while(true){ args.push(expr()); if(match('comma',',')) continue; match('paren',')'); break; }
        }
        return {type:'call',name:ident,args};
      }
      return {type:'ident',v:ident};
    }
    if(match('paren','(')){ const n=expr(); match('paren',')'); return n; }
    take(); return {type:'num',v:0};
  }
  return expr();
}

const AST_CACHE=new Map();
function parseFormula(f){
  f=f.replace(/_xlfn\./ig,'').replaceAll(';',',');
  if(AST_CACHE.has(f)) return AST_CACHE.get(f);
  const ast=Parser(tokenize(f));
  AST_CACHE.set(f,ast);
  return ast;
}

function truthy(x){
  if(x==null) return false;
  if(typeof x==='boolean') return x;
  if(typeof x==='number') return x!==0 && !Number.isNaN(x);
  if(x instanceof Date) return true;
  return String(x)!=='';
}
function compare(a,b,op){
  if(a instanceof Date) a=a.getTime();
  if(b instanceof Date) b=b.getTime();
  switch(op){
    case '=': return a==b;
    case '<>': return a!=b;
    case '<': return a<b;
    case '>': return a>b;
    case '<=': return a<=b;
    case '>=': return a>=b;
  }
  return false;
}

class Model{
  constructor(bundle){
    this.state=structuredClone(bundle.cells);
    this.cache=new Map();
    this.stack=new Set();
  }
  decode(enc){
    if(enc==null) return null;
    if(enc.t==='num') return Number(enc.v);
    if(enc.t==='bool') return Boolean(enc.v);
    if(enc.t==='date') return toDate(enc.v);
    return String(enc.v);
  }
  getCell(addr){ return this.state[addr.replaceAll('$','')]; }
  getValue(addr, env=null){
    addr=addr.replaceAll('$','');
    if(env && Object.prototype.hasOwnProperty.call(env, addr)) return env[addr];
    const key='c:'+addr;
    if(this.cache.has(key)) return this.cache.get(key);
    if(this.stack.has(addr)) return null;
    this.stack.add(addr);
    const cell=this.state[addr];
    let v=null;
    if(cell && cell.f) v=this.evalAst(parseFormula(cell.f), env||{});
    else v=this.decode(cell?.v);
    this.stack.delete(addr);
    this.cache.set(key,v);
    return v;
  }
  evalAst(node, env){
    switch(node.type){
      case 'num': return node.v;
      case 'str': return node.v;
      case 'cell': return this.getValue(node.v, env);
      case 'ident':
        if(Object.prototype.hasOwnProperty.call(env,node.v)) return env[node.v];
        if(node.v.toUpperCase()==='TRUE') return true;
        if(node.v.toUpperCase()==='FALSE') return false;
        return null;
      case 'un':{
        const x=this.evalAst(node.expr, env);
        const n=Number(x||0);
        return node.op==='-'? -n : n;
      }
      case 'bin':{
        const a=this.evalAst(node.left, env);
        const b=this.evalAst(node.right, env);
        if(['=','<>','<','>','<=','>='].includes(node.op)) return compare(a,b,node.op);
        const an=(a instanceof Date)? a.getTime():Number(a||0);
        const bn=(b instanceof Date)? b.getTime():Number(b||0);
        switch(node.op){
          case '+': return (typeof a==='string'||typeof b==='string')? String(a??'')+String(b??''): an+bn;
          case '-': return an-bn;
          case '*': return an*bn;
          case '/': return bn===0?0:an/bn;
          case '^': return Math.pow(an,bn);
        }
        return 0;
      }
      case 'call': return this.evalFunc(node.name, node.args, env);
    }
    return null;
  }
  evalFunc(name,args,env){
    const U=name.toUpperCase();
    if(U==='IF') return truthy(this.evalAst(args[0],env))? this.evalAst(args[1],env) : this.evalAst(args[2]||{type:'num',v:0},env);
    if(U==='AND') return args.every(a=>truthy(this.evalAst(a,env)));
    if(U==='MIN' || U==='MAX'){
      const nums=args.map(a=>this.evalAst(a,env)).filter(v=>v!=null && v!=='').map(v=>v instanceof Date? v.getTime():Number(v));
      if(!nums.length) return 0;
      return U==='MIN'? Math.min(...nums):Math.max(...nums);
    }
    if(U==='LET'){
      const local={...env};
      for(let i=0;i<args.length-1;i+=2){
        const nm=args[i].type==='ident'? args[i].v : (args[i].type==='str'?args[i].v:null);
        if(!nm) continue;
        local[nm]=this.evalAst(args[i+1], local);
      }
      return this.evalAst(args[args.length-1], local);
    }
    if(U==='YEARFRAC'){
      const d1=toDate(this.evalAst(args[0],env));
      const d2=toDate(this.evalAst(args[1],env));
      const basis=args[2]? Number(this.evalAst(args[2],env)):0;
      if(basis===1) return yearfracActualActual(d1,d2);
      return (d1&&d2)? diffDays(d1,d2)/365:0;
    }
    if(U==='EDATE') return edate(this.evalAst(args[0],env), this.evalAst(args[1],env));
    return null;
  }
}

function loadParams(){
  const raw=localStorage.getItem(PARAM_KEY);
  if(!raw) return structuredClone(BUNDLE.paramDefaults);
  try{ const o=JSON.parse(raw); return {...structuredClone(BUNDLE.paramDefaults), ...o}; }
  catch{ return structuredClone(BUNDLE.paramDefaults); }
}

function applyParams(model){
  const params=loadParams();
  for(const [addr,enc] of Object.entries(params)){
    if(enc==null) continue;
    if(!model.state[addr]) model.state[addr]={f:null,v:null,fmt:'General',input:false};
    model.state[addr].v=enc;
  }
}

function isDateFmt(fmt){
  fmt=String(fmt||'').toLowerCase();
  return fmt.includes('yy') || fmt.includes('dd') || fmt.includes('mm-');
}

function formatValue(val, fmt, label){
  if(val==null) return '';
  if(val instanceof Date) return formatDateFR(val);
  const f=String(fmt||'').toLowerCase();
  if(f.includes('" ans"')) return `${Number(val).toFixed(1)} ans`;
  if(f.includes('" mois"')) return `${Number(val).toFixed(1)} mois`;
  if(f.includes('%')) return `${(Number(val)*100).toFixed(0)}%`;
  if(fmt==='#,##0') return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(val||0));
  return (typeof val==='number')? new Intl.NumberFormat('fr-FR',{maximumFractionDigits:6}).format(val): String(val);
}

function buildGrid(model){
  const table=document.getElementById('grid');
  table.innerHTML='';
  const thead=document.createElement('thead');
  thead.innerHTML='<tr><th>Libellé</th><th>Scénario B</th><th>Scénario C</th></tr>';
  table.appendChild(thead);
  const tbody=document.createElement('tbody');

  for(const row of BUNDLE.render){
    const tr=document.createElement('tr');
    const [a,b,c]=row;
    const label=model.getValue(a);
    const tdA=document.createElement('td');
    tdA.textContent=String(label??'');
    tr.appendChild(tdA);

    for(const addr of [b,c]){
      const cell=model.getCell(addr);
      const td=document.createElement('td');
      if(cell?.input){
        td.className='cellInput';
        const decoded=model.decode(cell.v);
        let el;
        if(cell.opts){
          el=document.createElement('select');
          for(const opt of cell.opts){ const o=document.createElement('option'); o.value=opt; o.textContent=opt; el.appendChild(o); }
          el.value = decoded ?? cell.opts[0];
        } else if(isDateFmt(cell.fmt) || decoded instanceof Date){
          el=document.createElement('input'); el.type='date';
          el.value = decoded instanceof Date? decoded.toISOString().slice(0,10) : (decoded||'');
        } else {
          el=document.createElement('input'); el.type='number'; el.step='any';
          el.value = (typeof decoded==='number')? decoded : '';
        }
        el.addEventListener('input',()=>{
          const val=(el.tagName==='SELECT')? el.value : el.value;
          cell.v = (el.type==='date')? {t:'date',v:val} : (el.tagName==='SELECT'? {t:'str',v:val} : {t:'num',v:Number(val)});
          cell.f=null;
          model.cache.clear();
          recalc(model);
        });
        td.appendChild(el);
      } else {
        td.textContent = formatValue(model.getValue(addr), cell?.fmt, label);
      }
      tr.appendChild(td);
    }
    tbody.appendChild(tr);
  }
  table.appendChild(tbody);
}

function recalc(model){
  // evaluate all formula cells once
  for(const [addr,cell] of Object.entries(model.state)){
    if(cell?.f && !cell.input) model.getValue(addr);
  }
  buildGrid(model);
  document.getElementById('debug').textContent = JSON.stringify(model.state,null,2);
}

function exportCSV(model){
  const lines=['Adresse;Libellé;B;C'];
  for(const row of BUNDLE.render){
    const [a,b,c]=row;
    const lab=model.getValue(a);
    const vb=model.getValue(b);
    const vc=model.getValue(c);
    const fb = vb instanceof Date? formatDateFR(vb): String(vb??'');
    const fc = vc instanceof Date? formatDateFR(vc): String(vc??'');
    lines.push([a,String(lab??''),fb,fc].join(';'));
  }
  const blob=new Blob([lines.join('
')],{type:'text/csv;charset=utf-8'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a'); a.href=url; a.download='sim_rcc.csv';
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}

const model=new Model(BUNDLE);
applyParams(model);
for(const addr of BUNDLE.editableA){ if(model.state[addr]) model.state[addr].input=true; }
recalc(model);

document.getElementById('btnRecalc').onclick=()=>recalc(model);
document.getElementById('btnExport').onclick=()=>exportCSV(model);
